# ad9361
set_property  -dict {PACKAGE_PIN  D7  IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports rx_clk_in_p]
set_property  -dict {PACKAGE_PIN  D6  IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports rx_clk_in_n]
set_property  -dict {PACKAGE_PIN  E5  IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports rx_frame_in_p]
set_property  -dict {PACKAGE_PIN  D5  IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports rx_frame_in_n]
set_property  -dict {PACKAGE_PIN  E9  IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports rx_data_in_p[0]]
set_property  -dict {PACKAGE_PIN  D9  IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports rx_data_in_n[0]]
set_property  -dict {PACKAGE_PIN  G3  IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports rx_data_in_p[1]]
set_property  -dict {PACKAGE_PIN  F3  IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports rx_data_in_n[1]]
set_property  -dict {PACKAGE_PIN  G8  IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports rx_data_in_p[2]]
set_property  -dict {PACKAGE_PIN  F7  IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports rx_data_in_n[2]]
set_property  -dict {PACKAGE_PIN  G6  IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports rx_data_in_p[3]]
set_property  -dict {PACKAGE_PIN  F6  IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports rx_data_in_n[3]]
set_property  -dict {PACKAGE_PIN  G5  IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports rx_data_in_p[4]]
set_property  -dict {PACKAGE_PIN  F5  IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports rx_data_in_n[4]]
set_property  -dict {PACKAGE_PIN  F8  IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports rx_data_in_p[5]]
set_property  -dict {PACKAGE_PIN  E8  IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports rx_data_in_n[5]]
set_property  -dict {PACKAGE_PIN  F2  IOSTANDARD LVDS} [get_ports tx_clk_out_p]
set_property  -dict {PACKAGE_PIN  E2  IOSTANDARD LVDS} [get_ports tx_clk_out_n]
set_property  -dict {PACKAGE_PIN  D4  IOSTANDARD LVDS} [get_ports tx_frame_out_p]
set_property  -dict {PACKAGE_PIN  C4  IOSTANDARD LVDS} [get_ports tx_frame_out_n]
set_property  -dict {PACKAGE_PIN  B5  IOSTANDARD LVDS} [get_ports tx_data_out_p[0]]
set_property  -dict {PACKAGE_PIN  A5  IOSTANDARD LVDS} [get_ports tx_data_out_n[0]]
set_property  -dict {PACKAGE_PIN  A7  IOSTANDARD LVDS} [get_ports tx_data_out_p[1]]
set_property  -dict {PACKAGE_PIN  A6  IOSTANDARD LVDS} [get_ports tx_data_out_n[1]]
set_property  -dict {PACKAGE_PIN  A2  IOSTANDARD LVDS} [get_ports tx_data_out_p[2]]
set_property  -dict {PACKAGE_PIN  A1  IOSTANDARD LVDS} [get_ports tx_data_out_n[2]]
set_property  -dict {PACKAGE_PIN  B4  IOSTANDARD LVDS} [get_ports tx_data_out_p[3]]
set_property  -dict {PACKAGE_PIN  A4  IOSTANDARD LVDS} [get_ports tx_data_out_n[3]]
set_property  -dict {PACKAGE_PIN  C3  IOSTANDARD LVDS} [get_ports tx_data_out_p[4]]
set_property  -dict {PACKAGE_PIN  C2  IOSTANDARD LVDS} [get_ports tx_data_out_n[4]]
set_property  -dict {PACKAGE_PIN  A9  IOSTANDARD LVDS} [get_ports tx_data_out_p[5]]
set_property  -dict {PACKAGE_PIN  A8  IOSTANDARD LVDS} [get_ports tx_data_out_n[5]]

set_property  -dict {PACKAGE_PIN  B15  IOSTANDARD LVCMOS18} [get_ports gpio_en_agc]
set_property  -dict {PACKAGE_PIN  D11  IOSTANDARD LVCMOS18} [get_ports gpio_sync]
set_property  -dict {PACKAGE_PIN  H13  IOSTANDARD LVCMOS18} [get_ports gpio_resetb]
#set_property -dict {PACKAGE_PIN  A15  IOSTANDARD LVCMOS18} [get_ports enable]
#set_property -dict {PACKAGE_PIN  J14  IOSTANDARD LVCMOS18} [get_ports txnrx]
set_property  -dict {PACKAGE_PIN  E12  IOSTANDARD LVCMOS18} [get_ports gpio[0]]
set_property  -dict {PACKAGE_PIN  G10  IOSTANDARD LVCMOS18} [get_ports gpio[1]]
set_property  -dict {PACKAGE_PIN  H11  IOSTANDARD LVCMOS18} [get_ports gpio[2]]
set_property  -dict {PACKAGE_PIN  F11  IOSTANDARD LVCMOS18} [get_ports gpio[3]]
set_property  -dict {PACKAGE_PIN  H12  IOSTANDARD LVCMOS18} [get_ports gpio[4]]
set_property  -dict {PACKAGE_PIN  J12  IOSTANDARD LVCMOS18} [get_ports gpio[5]]
set_property  -dict {PACKAGE_PIN  D12  IOSTANDARD LVCMOS18} [get_ports gpio[6]]
set_property  -dict {PACKAGE_PIN  C12  IOSTANDARD LVCMOS18} [get_ports gpio[7]]
set_property  -dict {PACKAGE_PIN  C11  IOSTANDARD LVCMOS18} [get_ports gpio[8]]
set_property  -dict {PACKAGE_PIN  H14  IOSTANDARD LVCMOS18} [get_ports gpio[9]]
set_property  -dict {PACKAGE_PIN  L13  IOSTANDARD LVCMOS18} [get_ports gpio[10]]
set_property  -dict {PACKAGE_PIN  F12  IOSTANDARD LVCMOS18} [get_ports gpio[11]]

set_property  -dict {PACKAGE_PIN  H1  IOSTANDARD LVCMOS18  PULLTYPE PULLUP} [get_ports spi_csn]
set_property  -dict {PACKAGE_PIN  J6  IOSTANDARD LVCMOS18} [get_ports spi_clk]
set_property  -dict {PACKAGE_PIN  H6  IOSTANDARD LVCMOS18} [get_ports spi_mosi]
set_property  -dict {PACKAGE_PIN  J1  IOSTANDARD LVCMOS18} [get_ports spi_miso]

# clocks
create_clock -name rx_clk       -period  4 [get_ports rx_clk_in_p]
#create_clock -name ad9361_clk   -period  4 [get_pins i_system_1_wrapper/system_1_i/axi_ad9361/clk]

create_clock -period 16.276 -name dut_clk [get_pins i_system_1_wrapper/system_1_i/util_ad9361_divclk/clk_out]
# Clock Groups
set_clock_groups -asynchronous -group {dut_clk}
# EOF lemdig.xdc
