/*
 * This file is auto-generated by PetaLinux SDK 
 * DO NOT MODIFY this file, the modification will not persist
 */

#ifndef __PLNX_CONFIG_H
#define __PLNX_CONFIG_H

/* The following table includes the supported baudrates */


#define CONFIG_SYS_BAUDRATE_TABLE  { 4800, 9600, 19200, 38400, 57600, 115200 }



/* processor - psu_cortexa53_0 */
#define CONFIG_CPU_ARMV8
#define CONFIG_CLOCKS
#define CONFIG_REMAKE_ELF
#define CONFIG_BOARD_EARLY_INIT_R
#define CONFIG_BOARD_EARLY_INIT_F
#define CONFIG_ARM_DCC
#define CONFIG_MP

/* main_memory - psu_ddr_0 */

/* uart - psu_uart_0 */
#define PSSERIAL0	"psserial0=setenv stdout ttyPS0;setenv stdin ttyPS0\0"
#define SERIAL_MULTI	"serial=setenv stdout serial;setenv stdin serial\0"
#define CONSOLE_ARG	"console=console=ttyPS0,115200\0"
#define SERIAL_MULTI  "serial=setenv stdout serial;setenv stdin serial\0"
#define CONFIG_BAUDRATE	115200

/* ethernet - psu_ethernet_3 */
#define CONFIG_SYS_FAULT_ECHO_LINK_DOWN
#define PHY_ANEG_TIMEOUT 20000
#define CONFIG_MII
#define CONFIG_NET_MULTI
#define CONFIG_NETCONSOLE	1
#define CONFIG_SERVERIP	172.17.0.1
#define CONFIG_IPADDR

/* spi_flash - psu_qspi_0 */
#define XILINX_PS8_QSPI_CLK_FREQ_HZ	299999970
#define CONFIG_SF_DEFAULT_SPEED   (XILINX_PS8_QSPI_CLK_FREQ_HZ / 4)
#define CONFIG_MTD_UBI_WL_THRESHOLD 4096
#define CONFIG_MTD_UBI_BEB_LIMIT 0
#define CONFIG_CMD_UBI
#define CONFIG_RBTREE
#define CONFIG_CMD_UBIFS
#define CONFIG_LZO
#define CONFIG_CMD_MTDPARTS
#define CONFIG_MTD_DEVICE
#define CONFIG_MTD_PARTITIONS
#define CONFIG_SPI_FLASH_MTD

/* sdio - psu_sd_1 */
#define CONFIG_ZYNQ_SDHCI1
#define CONFIG_SUPPORT_VFAT
#define CONFIG_SUPPORT_EMMC_BOOT
#define CONFIG_ZYNQ_SDHCI_MAX_FREQ  200000000

/* rtc - psu_rtc */

/* i2c - psu_i2c_0 */
#define CONFIG_SYS_I2C_ZYNQ
#define CONFIG_SYS_I2C
#define CONFIG_SYS_I2C_ZYNQ_SLAVE	0
#define CONFIG_SYS_I2C_ZYNQ_SPEED 100000

/* zynq_ultra_ps_e_0 */
#define COUNTER_FREQUENCY 100000000

/* intc - psu_acpu_gic */
#define ACPU_GIC_BASEADDR	0xF9000000
#define CONFIG_GICV2	1
#define GICD_BASE	(ACPU_GIC_BASEADDR + 0x10000)
#define GICC_BASE (ACPU_GIC_BASEADDR + 0x20000)

/* FPGA */

/* Memory testing handling */
#define CONFIG_SYS_MEMTEST_START	0x0
#define CONFIG_SYS_MEMTEST_END	(0x0 + 0x1000)
#define CONFIG_SYS_LOAD_ADDR	(0x0 + 0x100000) /* default load address */
#define CONFIG_SYS_INIT_SP_ADDR	(CONFIG_SYS_LOAD_ADDR - GENERATED_GBL_DATA_SIZE)
#define CONFIG_NR_DRAM_BANKS	2

/* Size of malloc() pool */
#define SIZE	0x2000000
#define CONFIG_SYS_MALLOC_LEN	SIZE


/* BOOTP options */
#define CONFIG_BOOTP_SERVERIP
#define CONFIG_BOOTP_BOOTFILESIZE
#define CONFIG_BOOTP_BOOTPATH
#define CONFIG_BOOTP_GATEWAY
#define CONFIG_BOOTP_HOSTNAME
#define CONFIG_BOOTP_MAY_FAIL
#define CONFIG_BOOTP_DNS
#define CONFIG_BOOTP_SUBNETMASK
#define CONFIG_BOOTP_PXE

/*Command line configuration.*/
#define CONFIG_CMDLINE_EDITING
#define CONFIG_AUTO_COMPLETE

/* Miscellaneous configurable options */
#define CONFIG_SYS_CBSIZE	2048/* Console I/O Buffer Size      */
#define CONFIG_SYS_PBSIZE	(CONFIG_SYS_CBSIZE + sizeof(CONFIG_SYS_PROMPT) + 16)
#define CONFIG_SYS_BARGSIZE CONFIG_SYS_CBSIZE

/* Use the HUSH parser */
#define CONFIG_SYS_PROMPT_HUSH_PS2 "> "

#define CONFIG_ENV_VARS_UBOOT_CONFIG
#define CONFIG_ENV_OVERWRITE	/* Allow to overwrite the u-boot environment variables */

#define CONFIG_LMB

/* FDT support */
#define CONFIG_DISPLAY_BOARDINFO_LATE


/* Boot Argument Buffer Size */
#define CONFIG_SYS_MAXARGS      64      /* max number of command args */
#define CONFIG_SYS_LONGHELP

/* Initial memory map for Linux */
#define CONFIG_SYS_BOOTMAPSZ 0x8000000

/* Environment settings*/
#define CONFIG_ENV_SPI_MAX_HZ 108000000
#define CONFIG_ENV_OFFSET 0x07F00000
#define CONFIG_ENV_OFFSET_REDUND 0x07F40000
#define CONFIG_ENV_SIZE	0x40000
#define CONFIG_ENV_SECT_SIZE 0x20000
#define CONFIG_SYS_REDUNDAND_ENVIRONMENT 1

/* Xilinx-specific defines required when enabling Arasan NAND support */
#ifdef CONFIG_NAND_ARASAN
#define CONFIG_SYS_MAX_NAND_DEVICE	1
#define CONFIG_SYS_NAND_MAX_CHIPS 2
#define CONFIG_SYS_NAND_SELF_INIT
#define CONFIG_SYS_NAND_ONFI_DETECTION
#define CONFIG_MTD_DEVICE
#endif

/* PREBOOT */
#define CONFIG_PREBOOT	"sf probe"

/* Extra U-Boot Env settings */
#define CONFIG_EXTRA_ENV_SETTINGS \
	SERIAL_MULTI \
	CONSOLE_ARG \
	PSSERIAL0 \
	"ethaddr=00:0a:35:00:01:22\0" \
	"autoload=no\0" \
	"boot_targets=qspi0\0" \
	"default_bootcmd=for target in ${boot_targets}; do " \
	                          "run bootcmd_${target}; " \
	                  "done;\0" \
    "kernel_image=fitImage\0" \
    "boot_image=BOOT.bin\0" \
    "kernel_load_address=0x10000000\0" \
    "bootargs_base=earlycon clk_ignore_unused cma=850M uio_pdrv_genirq.of_id=generic-uio init_fatal_sh=true\0" \
    "bootkernel=bootm ${kernel_load_address}\0" \
    "kernel_qspi_offset=0x03000000\0" \
    "kernel_qspi_length=0x02000000\0" \
    "loadkernel_qspi0=sf read ${kernel_load_address} ${kernel_qspi_offset} ${kernel_qspi_length}\0" \
    "bootargs_ubi=root=/dev/ubi0_0 altroot=/dev/mmcblk0p2 ro rootfstype=ubifs altrootfstype=ext4 rootwait ubi.mtd=0 ubi.mtd=1\0" \
    "bootcmd_qspi0=setenv bootargs \"${bootargs_base} ${bootargs_ubi}\" && run loadkernel_qspi0 && run bootkernel\0" \
    "loadkernel_mmc0=fatload mmc 0 ${kernel_load_address} ${kernel_image}\0" \
    "bootargs_mmc=root=/dev/mmcblk0p2 ro rootfstype=ext4 rootwait\0" \
    "bootcmd_mmc0=setenv bootargs \"${bootargs_base} ${bootargs_mmc}\" && run loadkernel_mmc0 && run bootkernel\0" \
    "ipaddr=10.2.1.3\0"  \
    "serverip=10.2.1.6\0" \
    "netmask=255.255.255.0\0" \
    "loadkernel_tftp=tftpboot ${kernel_load_address} ${kernel_image}\0" \
    "bootcmd_tftp=run loadkernel_tftp && run bootkernel\0" \
    "update_kernel=run loadkernel_tftp && sf update 0x${fileaddr} ${kernel_qspi_offset} ${filesize}\0" \
    "update_uboot=tftpboot ${kernel_load_address} ${boot_image} && sf update 0x${fileaddr} 0x0 ${filesize}\0" \
    "update_rootfs=setenv bootargs \"${bootargs_base} install=1\" && run loadkernel_qspi0 && run bootkernel\0" \
""

/* BOOTCOMMAND */
#undef CONFIG_BOOTCOMMAND
#define CONFIG_BOOTCOMMAND	"run default_bootcmd"

#endif /* __PLNX_CONFIG_H */
